
name: Build
on:
  push:
    branches:
      - main
    tags:
      - "**"
  pull_request:
    branches:
      - main


jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        target:
        - x86_64-unknown-linux-gnu
    steps:
    - uses: styfle/cancel-workflow-action@0.6.0
      with:
        access_token: ${{ github.token }}

    - uses: actions/checkout@v2

    - uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        target: ${{ matrix.target }}
        override: true

    - name: build
      uses: actions-rs/cargo@v1
      with:
        use-cross: true
        command: build
        args: --target ${{ matrix.target }} --release

    - name: clippy
      uses: actions-rs/cargo@v1
      with:
        use-cross: true
        command: clippy
        args: --target ${{ matrix.target }} -- -D warnings

    - name: rustfmt
      uses: actions-rs/cargo@v1
      with:
        use-cross: true
        command: fmt
        args: -- --check

    - name: Create archive
      run: |
        tar \
          -C target/${{ matrix.target }}/release \
          -czvf cdbpatch-$(date -u +"%Y%m%d-%H%M%SUTC")-$(git rev-parse --short HEAD)-${{ matrix.target }}.tar.gz \
          cdbpatch

    - uses: actions/upload-artifact@v2
      with:
        path: cdbpatch-*.tar.gz

  deploy:
    if: startsWith(github.ref, 'refs/tags/')
    needs: [build]
    runs-on: ubuntu-latest
    steps:
    - name: Download build artifacts
      uses: actions/download-artifact@v2

    - name: Release
      uses: softprops/action-gh-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        files: artifact/cdbpatch-*.tar.gz

